dist: xenial
script: script/test
notifications:
  slack:
    rooms:
      - embassy-network:joFu5a311yAWnrF7DQGKtl02#modernomad-notify
  email:
    recipients:
      - craig@enspiral.com
    on_success: change
    on_failure: always
